export const conditions = {
  "clear sky": require("./Clear.json"),
  "céu limpo": require("./Clear.json"),
  "light rain": require("./moderateRain.json"),
  "chuva leve": require("./moderateRain.json"),
  "chuva fraca": require("./moderateRain.json"),
  "moderate rain": require("./moderateRain.json"),
  "chuva moderada": require("./moderateRain.json"),
  "heavy intensity rain": require("./rain.json"),
  "chuva de forte intensidade": require("./rain.json"),
  "very heavy rain": require("./rain.json"),
  "chuva muito forte": require("./rain.json"),
  "freezing rain": require("./rain.json"),
  "chuva congelante": require("./rain.json"),
  "extreme rain": require("./rain.json"),
  "chuva extrema": require("./rain.json"),
  "chuva de banho": require("./rain.json"),
  "chuva forte": require("./rain.json"),
  "Chuva irregular": require("./rain.json"),
  "shower rain": require("./rain.json"),
  'freezing rain':require("./Snow.json"),
'light intensity shower rain':require('./Mist.json'),
'intensidade de luz chuveiro chuva':require('./Mist.json'),
'chuva de banho':require('./rain.json'),
'chuva forte':require('./rain.json'),
'Chuva irregular':require('./rain.json'),
  "heavy intensity shower rain": require("./rain.json"),
  "ragged shower rain": require("./rain.json"),
  "light snow": require("./Snow.json"),
  'snow': require("./Snow.json"),
  "heavy snow": require("./Snow.json"),
  'sleet': require("./Snow.json"),
  "light shower sleet": require("./Snow.json"),
  "light sleet": require("./Snow.json"),
  "light rain and snow": require("./Snow.json"),
  "rain and snow": require("./Snow.json"),
  "light shower snow": require("./Snow.json"),
  "shower snow": require("./Snow.json"),
  "heavy shower snow": require("./Snow.json"),
  "névoa leve": require("./Snow.json"),
  'névoa': require("./Snow.json"),
  "névoa  intensa": require("./Snow.json"),
  'granizo': require("./Snow.json"),
  "chuva leve com granizo": require("./Snow.json"),
  "chuva leve com granizo": require("./Snow.json"),
  "chuva leve com neve": require("./Snow.json"),
  "chuva e neve": require("./Snow.json"),
  "chuva leve com neve": require("./Snow.json"),
  "chuva com neve": require("./Snow.json"),
  "neve intensa": require("./Snow.json"),
'mist':require('./Mist.json'),
'smoke':require('./Mist.json'),
'haze':require('./Mist.json'),
'sand/dust whirls':require('./Mist.json'),
'fog':require('./Mist.json'),
'sand':require('./Mist.json'),
'dust':require('./Mist.json'),
'volcanic ash':require('./Mist.json'),
'squalls':require('./Mist.json'),
'tornado':require('./Mist.json'),
'fumaça': require('./Mist.json'),
'neblina': require('./Mist.json'),
'redemoinhos de areia/poeira': require('./Mist.json'),
'nevoeiro': require('./Mist.json'),
'areia': require('./Mist.json'),
'poeira': require('./Mist.json'),
'cinzas vulcânicas': require('./Mist.json'),
'rajadas': require('./Mist.json'),
  "broken clouds": require("./Cloudy.json"),
  "nuvens quebradas": require("./Cloudy.json"),
 'few clouds': require("./Cloudy.json"),
 'scattered clouds':require("./Cloudy.json"),
 'broken clouds':require("./Cloudy.json"),
  'overcast clouds':require("./Cloudy.json"),
  'céu pouco nublado': require("./Cloudy.json"),
  'nuvens dispersas': require("./Cloudy.json"),
  'nuvens quebradas': require("./Cloudy.json"),
  'nuvens encobertas': require("./Cloudy.json"),
  'nublado': require("./Cloud.json"),
'light intensity drizzle': require("./rain.json"),
'drizzle': require("./rain.json"),
'heavy intensity drizzle': require("./rain.json"),
'light intensity drizzle': require("./rain.json"),
'drizzle rain': require("./rain.json"),
'heavy intensity drizzle': require("./rain.json"),
'shower rain and drizzle': require("./rain.json"),
'heavy shower rain and drizzle': require("./rain.json"),
'shower drizzle': require("./rain.json"),
'chuvisco de intensidade leve': require("./rain.json"),
'chuvisco': require("./rain.json"),
'chuvisco de intensidade forte': require("./rain.json"),
'chuvisco de intensidade leve': require("./rain.json"),
'chuvisco de chuva': require("./rain.json"),
'chuvisco de intensidade forte': require("./rain.json"),
'chuva e chuvisco': require("./rain.json"),
'chuva forte e chuvisco': require("./rain.json"),
'chuvisco de chuva': require("./rain.json"),
'thunderstorm with light rain': require('./thunderstorm.json'),
'thunderstorm with light rain': require('./thunderstorm.json'),
'thunderstorm with rain': require('./thunderstorm.json'),
'thunderstorm with heavy rain': require('./thunderstorm.json'),
'light thunderstorm': require('./thunderstorm.json'),
'thunderstorm': require('./thunderstorm.json'),
'heavy thunderstorm': require('./thunderstorm.json'),
'ragged thunderstorm': require('./thunderstorm.json'),
'thunderstorm with light drizzle': require('./thunderstorm.json'),
'thunderstorm with drizzle': require('./thunderstorm.json'),
'thunderstorm with heavy drizzle': require('./thunderstorm.json'),
'tempestade com chuva leve': require('./thunderstorm.json'),
'tempestade com chuva leve': require('./thunderstorm.json'),
'tempestade com chuva': require('./thunderstorm.json'),
'tempestade com chuva intensa': require('./thunderstorm.json'),
'tempestade leve': require('./thunderstorm.json'),
'tempestade': require('./thunderstorm.json'),
'tempestade intensa': require('./thunderstorm.json'),
'tempestade irregular': require('./thunderstorm.json'),
'tempestade com garoa leve': require('./thunderstorm.json'),
'tempestade com garoa': require('./thunderstorm.json'),
'tempestade com garoa intensa': require('./thunderstorm.json'),
Rain: require("./rain.json"),
  Clear: require("./Clear.json"),
};
